import hashlib
import os
import secrets
import sqlite3
import threading
import time
from datetime import date, datetime
from decimal import Decimal

from werkzeug.security import check_password_hash, generate_password_hash


DB_NAME = os.getenv("SQLITE_PATH", "financeiro.db")
DATABASE_URL = os.getenv("DATABASE_URL")
_POSTGRES_POOL = None
_POSTGRES_POOL_URL = None
_POSTGRES_POOL_LOCK = threading.Lock()


def _normalizar_valor(valor):
    if isinstance(valor, Decimal):
        return str(valor)
    if isinstance(valor, (date, datetime)):
        return valor.isoformat()
    return valor


def _normalizar_linha(linha):
    if linha is None:
        return None
    dados = dict(linha)
    return {chave: _normalizar_valor(valor) for chave, valor in dados.items()}


class CursorAdapter:
    def __init__(self, cursor, postgres=False):
        self._cursor = cursor
        self._postgres = postgres

    def execute(self, query, params=()):
        if self._postgres:
            query = query.replace("?", "%s")
            parametros = params
        else:
            parametros = tuple(_normalizar_valor(valor) for valor in params)
        self._cursor.execute(query, parametros)
        return self

    def executemany(self, query, params):
        if self._postgres:
            query = query.replace("?", "%s")
            parametros = params
        else:
            parametros = [
                tuple(_normalizar_valor(valor) for valor in linha) for linha in params
            ]
        self._cursor.executemany(query, parametros)
        return self

    def fetchone(self):
        return _normalizar_linha(self._cursor.fetchone())

    def fetchall(self):
        return [_normalizar_linha(row) for row in self._cursor.fetchall()]

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def lastrowid(self):
        return getattr(self._cursor, "lastrowid", None)


class ConnectionAdapter:
    def __init__(self, connection, postgres=False, release=None):
        self._connection = connection
        self.postgres = postgres
        self._release = release
        self._closed = False

    def cursor(self):
        return CursorAdapter(self._connection.cursor(), self.postgres)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        if self._closed:
            return
        self._closed = True
        if self._release:
            self._release(self._connection)
        else:
            self._connection.close()


def conectar():
    if DATABASE_URL:
        global _POSTGRES_POOL, _POSTGRES_POOL_URL
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool

        if _POSTGRES_POOL is None or _POSTGRES_POOL_URL != DATABASE_URL:
            with _POSTGRES_POOL_LOCK:
                if _POSTGRES_POOL is None or _POSTGRES_POOL_URL != DATABASE_URL:
                    if _POSTGRES_POOL is not None:
                        _POSTGRES_POOL.close()
                    _POSTGRES_POOL = ConnectionPool(
                        conninfo=DATABASE_URL,
                        min_size=0,
                        max_size=max(1, int(os.getenv("DATABASE_POOL_SIZE", "4"))),
                        timeout=10,
                        max_idle=60,
                        kwargs={"row_factory": dict_row, "connect_timeout": 10},
                        check=ConnectionPool.check_connection,
                        open=True,
                        name="financeapp",
                    )
                    _POSTGRES_POOL_URL = DATABASE_URL
        connection = _POSTGRES_POOL.getconn()
        return ConnectionAdapter(
            connection, postgres=True, release=_POSTGRES_POOL.putconn
        )

    connection = sqlite3.connect(DB_NAME, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return ConnectionAdapter(connection)


def _colunas(cursor, tabela, postgres):
    if postgres:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ?",
            (tabela,),
        )
        return {row["column_name"] for row in cursor.fetchall()}
    cursor.execute(f"PRAGMA table_info({tabela})")
    return {row["name"] for row in cursor.fetchall()}


def executar_migracoes():
    """Apply versioned, idempotent schema migrations on startup."""
    conn = conectar()
    cursor = conn.cursor()
    postgres = conn.postgres
    identity = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    money = "NUMERIC(14,2)" if postgres else "NUMERIC"
    date_type = "DATE" if postgres else "TEXT"

    try:
        if postgres:
            cursor.execute("SELECT pg_advisory_xact_lock(184726391)")

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS usuarios (
                id {identity},
                nome TEXT NOT NULL,
                cpf TEXT UNIQUE,
                email TEXT NOT NULL UNIQUE,
                senha TEXT NOT NULL,
                perfil TEXT NOT NULL DEFAULT 'Padrão',
                ativo INTEGER NOT NULL DEFAULT 1,
                session_version INTEGER NOT NULL DEFAULT 1,
                must_change_password INTEGER NOT NULL DEFAULT 0,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS lancamentos (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                data {date_type} NOT NULL,
                tipo TEXT NOT NULL,
                descricao TEXT NOT NULL,
                valor {money} NOT NULL,
                obs TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS compras (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                data {date_type} NOT NULL,
                categoria TEXT NOT NULL,
                item TEXT NOT NULL,
                quantidade {money} NOT NULL,
                valor_unitario {money} NOT NULL,
                valor_total {money} NOT NULL,
                comprado INTEGER NOT NULL DEFAULT 0,
                obs TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS metas (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                titulo TEXT NOT NULL,
                categoria TEXT NOT NULL,
                valor_alvo {money} NOT NULL,
                valor_atual {money} NOT NULL DEFAULT 0,
                data_limite {date_type},
                prioridade TEXT NOT NULL DEFAULT 'Média',
                status TEXT NOT NULL DEFAULT 'Ativa',
                descricao TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS agenda (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                titulo TEXT NOT NULL,
                data {date_type} NOT NULL,
                horario TEXT,
                categoria TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'Pendente',
                descricao TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS meta_movimentacoes (
                id {identity},
                meta_id INTEGER NOT NULL REFERENCES metas(id) ON DELETE CASCADE,
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                tipo TEXT NOT NULL,
                valor {money} NOT NULL,
                descricao TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS configuracoes (
                id {identity},
                tipo_pix TEXT NOT NULL,
                chave_pix TEXT NOT NULL,
                nome_recebedor TEXT NOT NULL,
                banco TEXT NOT NULL,
                valor_cadastro_centavos INTEGER NOT NULL DEFAULT 0,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS solicitacoes_cadastro (
                id {identity},
                public_token TEXT UNIQUE,
                nome TEXT NOT NULL,
                cpf TEXT NOT NULL,
                email TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pendente',
                usuario_criado INTEGER NOT NULL DEFAULT 0,
                valor_centavos INTEGER NOT NULL DEFAULT 0,
                asaas_customer_id TEXT,
                external_payment_id TEXT UNIQUE,
                pix_payload TEXT,
                pix_expiration TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                pago_em TIMESTAMP
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS rate_limits (
                chave TEXT PRIMARY KEY,
                tentativas INTEGER NOT NULL,
                janela_inicio INTEGER NOT NULL
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS password_reset_tokens (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                token_hash TEXT NOT NULL UNIQUE,
                expires_at INTEGER NOT NULL,
                used_at INTEGER,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)

        timestamp_addition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP" if postgres else "TIMESTAMP"
        additions = {
            "usuarios": {
                "session_version": "INTEGER NOT NULL DEFAULT 1",
                "must_change_password": "INTEGER NOT NULL DEFAULT 0",
                "criado_em": timestamp_addition,
            },
            "lancamentos": {"criado_em": timestamp_addition},
            "compras": {"criado_em": timestamp_addition},
            "configuracoes": {
                "valor_cadastro_centavos": "INTEGER NOT NULL DEFAULT 0",
            },
            "solicitacoes_cadastro": {
                "public_token": "TEXT",
                "nome": "TEXT",
                "valor_centavos": "INTEGER NOT NULL DEFAULT 0",
                "asaas_customer_id": "TEXT",
                "external_payment_id": "TEXT",
                "pix_payload": "TEXT",
                "pix_expiration": "TEXT",
                "atualizado_em": timestamp_addition,
            },
        }
        for tabela, colunas in additions.items():
            existentes = _colunas(cursor, tabela, postgres)
            for coluna, definicao in colunas.items():
                if coluna not in existentes:
                    cursor.execute(
                        f"ALTER TABLE {tabela} ADD COLUMN {coluna} {definicao}"
                    )

        cursor.execute(
            "SELECT id FROM solicitacoes_cadastro "
            "WHERE public_token IS NULL OR public_token = ''"
        )
        for row in cursor.fetchall():
            cursor.execute(
                "UPDATE solicitacoes_cadastro SET public_token = ? WHERE id = ?",
                (secrets.token_urlsafe(32), row["id"]),
            )

        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (2,))
        migration_2_aplicada = cursor.fetchone() is not None
        if postgres and not migration_2_aplicada:
            cursor.execute(
                "ALTER TABLE lancamentos ALTER COLUMN valor TYPE NUMERIC(14,2) "
                "USING valor::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN quantidade TYPE NUMERIC(14,2) "
                "USING quantidade::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN valor_unitario TYPE NUMERIC(14,2) "
                "USING valor_unitario::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN valor_total TYPE NUMERIC(14,2) "
                "USING valor_total::numeric"
            )
        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (3,))
        migration_3_aplicada = cursor.fetchone() is not None
        if postgres and not migration_3_aplicada:
            cursor.execute(
                "ALTER TABLE lancamentos ALTER COLUMN data TYPE DATE USING data::date"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN data TYPE DATE USING data::date"
            )

        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitacoes_public_token "
            "ON solicitacoes_cadastro(public_token)"
        )
        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitacoes_payment_id "
            "ON solicitacoes_cadastro(external_payment_id) "
            "WHERE external_payment_id IS NOT NULL"
        )

        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_lancamentos_usuario_data "
            "ON lancamentos(usuario_id, data)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_lancamentos_usuario_id "
            "ON lancamentos(usuario_id, id DESC)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_compras_usuario_data "
            "ON compras(usuario_id, data)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_compras_usuario_id "
            "ON compras(usuario_id, id DESC)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_metas_usuario_status "
            "ON metas(usuario_id, status)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_agenda_usuario_data "
            "ON agenda(usuario_id, data)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_meta_movimentacoes_meta "
            "ON meta_movimentacoes(meta_id, criado_em)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_solicitacoes_status "
            "ON solicitacoes_cadastro(status)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_password_reset_usuario "
            "ON password_reset_tokens(usuario_id, expires_at)"
        )

        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (4,))
        migration_4_aplicada = cursor.fetchone() is not None
        admin_email = os.getenv("ADMIN_EMAIL", "").strip().lower()
        admin_password = os.getenv("ADMIN_PASSWORD", "")
        if not migration_4_aplicada and admin_email and admin_password:
            cursor.execute(
                "UPDATE usuarios SET senha = ?, perfil = 'Administrativo', ativo = 1, "
                "must_change_password = 1, session_version = session_version + 1 "
                "WHERE email = ?",
                (generate_password_hash(admin_password), admin_email),
            )

        # Version 5 reapplies the one-time reset after correcting the production
        # secret. It remains idempotent and never runs again after being recorded.
        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (5,))
        migration_5_aplicada = cursor.fetchone() is not None
        if not migration_5_aplicada and admin_email and admin_password:
            cursor.execute(
                "UPDATE usuarios SET senha = ?, perfil = 'Administrativo', ativo = 1, "
                "must_change_password = 1, session_version = session_version + 1 "
                "WHERE email = ?",
                (generate_password_hash(admin_password), admin_email),
            )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (1,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (2,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (3,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (4,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (5,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (6,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (7,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (8,),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def criar_tabelas():
    executar_migracoes()


def criar_admin_inicial():
    email = os.getenv("ADMIN_EMAIL", "").strip().lower()
    senha = os.getenv("ADMIN_PASSWORD", "")
    nome = os.getenv("ADMIN_NAME", "Administrador").strip()
    if not email or not senha:
        return

    conn = conectar()
    cursor = conn.cursor()
    try:
        command = "INSERT INTO" if conn.postgres else "INSERT OR IGNORE INTO"
        suffix = " ON CONFLICT (email) DO NOTHING" if conn.postgres else ""
        cursor.execute(
            f"{command} usuarios "
            "(nome, cpf, email, senha, perfil, must_change_password) "
            "VALUES (?, ?, ?, ?, ?, ?)" + suffix,
            (nome, None, email, generate_password_hash(senha), "Administrativo", 1),
        )
        cursor.execute("SELECT id, senha FROM usuarios WHERE email = ?", (email,))
        existente = cursor.fetchone()
        if existente and check_password_hash(existente["senha"], senha):
            cursor.execute(
                "UPDATE usuarios SET must_change_password = 1 WHERE id = ?",
                (existente["id"],),
            )
        conn.commit()
    finally:
        conn.close()


def buscar_usuario(email, senha):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, senha, perfil, ativo, session_version, "
        "must_change_password FROM usuarios WHERE email = ?",
        (email.strip().lower(),),
    )
    usuario = cursor.fetchone()
    conn.close()
    if not usuario or usuario["ativo"] != 1:
        return None
    if not check_password_hash(usuario["senha"], senha):
        return None
    usuario.pop("senha", None)
    return usuario


def buscar_usuario_por_id(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, perfil, ativo, session_version, "
        "must_change_password FROM usuarios WHERE id = ?",
        (usuario_id,),
    )
    usuario = cursor.fetchone()
    conn.close()
    return usuario


def listar_usuarios():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, perfil, ativo, must_change_password "
        "FROM usuarios ORDER BY nome ASC"
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def criar_usuario(nome, cpf, email, senha, perfil, must_change_password=0):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO usuarios "
        "(nome, cpf, email, senha, perfil, must_change_password) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (
            nome,
            cpf,
            email.strip().lower(),
            generate_password_hash(senha),
            perfil,
            must_change_password,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_dados_usuario(usuario_id, nome, email, perfil):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET nome = ?, email = ?, perfil = ?, "
        "session_version = session_version + 1 WHERE id = ?",
        (nome, email.strip().lower(), perfil, usuario_id),
    )
    conn.commit()
    conn.close()


def atualizar_status_usuario(usuario_id, ativo):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET ativo = ?, session_version = session_version + 1 "
        "WHERE id = ?",
        (1 if ativo else 0, usuario_id),
    )
    conn.commit()
    conn.close()


def alterar_senha_usuario(usuario_id, nova_senha, force_change=1):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET senha = ?, must_change_password = ?, "
        "session_version = session_version + 1 WHERE id = ?",
        (generate_password_hash(nova_senha), force_change, usuario_id),
    )
    conn.commit()
    conn.close()


def alterar_senha_propria(usuario_id, senha_atual, nova_senha):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT senha, session_version FROM usuarios WHERE id = ? AND ativo = 1",
        (usuario_id,),
    )
    usuario = cursor.fetchone()
    if not usuario or not check_password_hash(usuario["senha"], senha_atual):
        conn.close()
        return None
    nova_versao = int(usuario["session_version"]) + 1
    cursor.execute(
        "UPDATE usuarios SET senha = ?, must_change_password = 0, "
        "session_version = ? WHERE id = ?",
        (generate_password_hash(nova_senha), nova_versao, usuario_id),
    )
    conn.commit()
    conn.close()
    return nova_versao


def criar_token_recuperacao(email, token, validade_segundos=1800):
    """Create a single-use reset token, storing only its SHA-256 digest."""
    agora = int(time.time())
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "SELECT id, nome, email FROM usuarios WHERE email = ? AND ativo = 1",
            (email.strip().lower(),),
        )
        usuario = cursor.fetchone()
        if not usuario:
            return None
        cursor.execute(
            "DELETE FROM password_reset_tokens "
            "WHERE usuario_id = ? OR expires_at <= ?",
            (usuario["id"], agora),
        )
        cursor.execute(
            "INSERT INTO password_reset_tokens "
            "(usuario_id, token_hash, expires_at) VALUES (?, ?, ?)",
            (usuario["id"], token_hash, agora + validade_segundos),
        )
        conn.commit()
        return usuario
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def token_recuperacao_valido(token):
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT 1 AS valido FROM password_reset_tokens pr "
        "JOIN usuarios u ON u.id = pr.usuario_id "
        "WHERE pr.token_hash = ? AND pr.used_at IS NULL "
        "AND pr.expires_at > ? AND u.ativo = 1",
        (token_hash, int(time.time())),
    )
    valido = cursor.fetchone() is not None
    conn.close()
    return valido


def redefinir_senha_com_token(token, nova_senha):
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    agora = int(time.time())
    conn = conectar()
    cursor = conn.cursor()
    try:
        lock = " FOR UPDATE" if conn.postgres else ""
        cursor.execute(
            "SELECT pr.id, pr.usuario_id FROM password_reset_tokens pr "
            "JOIN usuarios u ON u.id = pr.usuario_id "
            "WHERE pr.token_hash = ? AND pr.used_at IS NULL "
            "AND pr.expires_at > ? AND u.ativo = 1" + lock,
            (token_hash, agora),
        )
        registro = cursor.fetchone()
        if not registro:
            conn.rollback()
            return False
        cursor.execute(
            "UPDATE usuarios SET senha = ?, must_change_password = 0, "
            "session_version = session_version + 1 WHERE id = ?",
            (generate_password_hash(nova_senha), registro["usuario_id"]),
        )
        cursor.execute(
            "UPDATE password_reset_tokens SET used_at = ? "
            "WHERE id = ? AND used_at IS NULL",
            (agora, registro["id"]),
        )
        cursor.execute(
            "DELETE FROM password_reset_tokens "
            "WHERE usuario_id = ? AND id <> ?",
            (registro["usuario_id"], registro["id"]),
        )
        conn.commit()
        return True
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def excluir_usuario(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM lancamentos WHERE usuario_id = ?", (usuario_id,))
        cursor.execute("DELETE FROM compras WHERE usuario_id = ?", (usuario_id,))
        cursor.execute("DELETE FROM agenda WHERE usuario_id = ?", (usuario_id,))
        cursor.execute("DELETE FROM usuarios WHERE id = ?", (usuario_id,))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def buscar_configuracoes():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM configuracoes ORDER BY id LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return row


def salvar_ou_atualizar_configuracoes(
    tipo_pix, chave_pix, nome_recebedor, banco, valor_cadastro_centavos
):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT id FROM configuracoes ORDER BY id LIMIT 1")
    existente = cursor.fetchone()
    if existente:
        cursor.execute(
            "UPDATE configuracoes SET tipo_pix = ?, chave_pix = ?, "
            "nome_recebedor = ?, banco = ?, valor_cadastro_centavos = ?, "
            "atualizado_em = CURRENT_TIMESTAMP "
            "WHERE id = ?",
            (
                tipo_pix,
                chave_pix,
                nome_recebedor,
                banco,
                valor_cadastro_centavos,
                existente["id"],
            ),
        )
    else:
        cursor.execute(
            "INSERT INTO configuracoes "
            "(tipo_pix, chave_pix, nome_recebedor, banco, valor_cadastro_centavos) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                tipo_pix,
                chave_pix,
                nome_recebedor,
                banco,
                valor_cadastro_centavos,
            ),
        )
    conn.commit()
    conn.close()


def email_usuario_existe(email):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS existe FROM usuarios WHERE email = ?", (email,))
    existe = cursor.fetchone() is not None
    conn.close()
    return existe


def cpf_usuario_existe(cpf):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS existe FROM usuarios WHERE cpf = ?", (cpf,))
    existe = cursor.fetchone() is not None
    conn.close()
    return existe


def criar_ou_buscar_solicitacao(nome, cpf, email, valor_centavos):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT public_token, nome, status, valor_centavos, asaas_customer_id, external_payment_id, "
        "pix_payload, pix_expiration FROM solicitacoes_cadastro "
        "WHERE cpf = ? AND email = ? AND valor_centavos = ? "
        "ORDER BY id DESC LIMIT 1",
        (cpf, email, valor_centavos),
    )
    existente = cursor.fetchone()
    if existente:
        if not existente.get("nome"):
            cursor.execute(
                "UPDATE solicitacoes_cadastro SET nome = ?, atualizado_em = CURRENT_TIMESTAMP "
                "WHERE public_token = ?",
                (nome, existente["public_token"]),
            )
            existente["nome"] = nome
            conn.commit()
        conn.close()
        return existente

    token = secrets.token_urlsafe(32)
    returning = (
        " RETURNING public_token, nome, status, asaas_customer_id, "
        "external_payment_id, pix_payload, pix_expiration, valor_centavos"
        if conn.postgres else ""
    )
    cursor.execute(
        "INSERT INTO solicitacoes_cadastro "
        "(public_token, nome, cpf, email, valor_centavos) VALUES (?, ?, ?, ?, ?)" + returning,
        (token, nome, cpf, email, valor_centavos),
    )
    if conn.postgres:
        row = cursor.fetchone()
    else:
        row = {
            "public_token": token,
            "nome": nome,
            "status": "pendente",
            "valor_centavos": valor_centavos,
            "asaas_customer_id": None,
            "external_payment_id": None,
            "pix_payload": None,
            "pix_expiration": None,
        }
    conn.commit()
    conn.close()
    return row


def buscar_status_solicitacao(token):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT public_token, nome, status, usuario_criado, valor_centavos, "
        "external_payment_id, pix_payload, pix_expiration "
        "FROM solicitacoes_cadastro "
        "WHERE public_token = ?",
        (token,),
    )
    row = cursor.fetchone()
    conn.close()
    return row


def salvar_pagamento_asaas(token, customer_id, payment_id, pix_payload, pix_expiration):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE solicitacoes_cadastro SET asaas_customer_id = ?, external_payment_id = ?, "
        "pix_payload = ?, pix_expiration = ?, atualizado_em = CURRENT_TIMESTAMP "
        "WHERE public_token = ? AND status = 'pendente'",
        (customer_id, payment_id, pix_payload, pix_expiration, token),
    )
    alteradas = cursor.rowcount
    conn.commit()
    conn.close()
    return alteradas == 1


def confirmar_pagamento(token, external_payment_id, valor_centavos):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE solicitacoes_cadastro SET status = 'pago', pago_em = CURRENT_TIMESTAMP, "
        "atualizado_em = CURRENT_TIMESTAMP "
        "WHERE public_token = ? AND external_payment_id = ? "
        "AND valor_centavos = ? AND status = 'pendente'",
        (token, external_payment_id, valor_centavos),
    )
    alteradas = cursor.rowcount
    if alteradas == 0:
        cursor.execute(
            "SELECT 1 AS confirmado FROM solicitacoes_cadastro "
            "WHERE public_token = ? AND external_payment_id = ? "
            "AND valor_centavos = ? AND status = 'pago'",
            (token, external_payment_id, valor_centavos),
        )
        alteradas = 1 if cursor.fetchone() else 0
    conn.commit()
    conn.close()
    return alteradas == 1


def finalizar_cadastro(token, nome, email, senha):
    conn = conectar()
    cursor = conn.cursor()
    try:
        lock = " FOR UPDATE" if conn.postgres else ""
        cursor.execute(
            "SELECT nome, cpf, email, status, usuario_criado FROM solicitacoes_cadastro "
            "WHERE public_token = ?" + lock,
            (token,),
        )
        solicitacao = cursor.fetchone()
        if not solicitacao:
            return "nao_encontrada"
        if solicitacao["status"] != "pago":
            return "nao_pago"
        if solicitacao["usuario_criado"] == 1:
            return "ja_criado"
        if solicitacao["email"].lower() != email.lower():
            return "email_invalido"
        if (solicitacao.get("nome") or "").strip() != nome.strip():
            return "nome_invalido"

        cursor.execute(
            "INSERT INTO usuarios (nome, cpf, email, senha, perfil) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                solicitacao["nome"].strip(),
                solicitacao["cpf"],
                email.lower(),
                generate_password_hash(senha),
                "Padrão",
            ),
        )
        cursor.execute(
            "UPDATE solicitacoes_cadastro SET usuario_criado = 1, "
            "atualizado_em = CURRENT_TIMESTAMP WHERE public_token = ?",
            (token,),
        )
        conn.commit()
        return "ok"
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def rate_limit_permitir(chave, limite, janela_segundos):
    agora = int(time.time())
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "INSERT INTO rate_limits(chave, tentativas, janela_inicio) "
            "VALUES (?, 1, ?) ON CONFLICT(chave) DO UPDATE SET "
            "tentativas = CASE WHEN ? - rate_limits.janela_inicio >= ? "
            "THEN 1 ELSE rate_limits.tentativas + 1 END, "
            "janela_inicio = CASE WHEN ? - rate_limits.janela_inicio >= ? "
            "THEN ? ELSE rate_limits.janela_inicio END "
            "RETURNING tentativas",
            (chave, agora, agora, janela_segundos, agora, janela_segundos, agora),
        )
        row = cursor.fetchone()
        cursor.execute(
            "DELETE FROM rate_limits WHERE janela_inicio < ?",
            (agora - 7 * 24 * 60 * 60,),
        )
        conn.commit()
        return int(row["tentativas"]) <= limite
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def rate_limit_limpar(chave):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM rate_limits WHERE chave = ?", (chave,))
    conn.commit()
    conn.close()


def _listar_por_usuario(tabela, usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        f"SELECT * FROM {tabela} WHERE usuario_id = ? ORDER BY id DESC",
        (usuario_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def listar_lancamentos(usuario_id):
    return _listar_por_usuario("lancamentos", usuario_id)


def criar_lancamento(usuario_id, data, tipo, descricao, valor, obs):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO lancamentos "
        "(usuario_id, data, tipo, descricao, valor, obs) VALUES (?, ?, ?, ?, ?, ?)",
        (usuario_id, data, tipo, descricao, Decimal(str(valor)), obs),
    )
    conn.commit()
    conn.close()


def atualizar_lancamento(usuario_id, id, data, tipo, descricao, valor, obs):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE lancamentos SET data = ?, tipo = ?, descricao = ?, valor = ?, obs = ? "
        "WHERE id = ? AND usuario_id = ?",
        (data, tipo, descricao, Decimal(str(valor)), obs, id, usuario_id),
    )
    conn.commit()
    conn.close()


def excluir_lancamento(usuario_id, id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM lancamentos WHERE id = ? AND usuario_id = ?",
        (id, usuario_id),
    )
    conn.commit()
    conn.close()


def listar_compras(usuario_id):
    return _listar_por_usuario("compras", usuario_id)


def criar_compra(usuario_id, data, categoria, item, quantidade, valor_unitario, obs):
    quantidade = Decimal(str(quantidade))
    valor_unitario = Decimal(str(valor_unitario))
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO compras (usuario_id, data, categoria, item, quantidade, "
        "valor_unitario, valor_total, comprado, obs) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)",
        (
            usuario_id,
            data,
            categoria,
            item,
            quantidade,
            valor_unitario,
            quantidade * valor_unitario,
            obs,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_compra(usuario_id, id, data, categoria, item, quantidade, valor_unitario, obs):
    quantidade = Decimal(str(quantidade))
    valor_unitario = Decimal(str(valor_unitario))
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE compras SET data = ?, categoria = ?, item = ?, quantidade = ?, "
        "valor_unitario = ?, valor_total = ?, obs = ? WHERE id = ? AND usuario_id = ?",
        (
            data,
            categoria,
            item,
            quantidade,
            valor_unitario,
            quantidade * valor_unitario,
            obs,
            id,
            usuario_id,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_status_compra(usuario_id, id, comprado):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE compras SET comprado = ? WHERE id = ? AND usuario_id = ?",
        (1 if comprado else 0, id, usuario_id),
    )
    conn.commit()
    conn.close()


def excluir_compra(usuario_id, id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM compras WHERE id = ? AND usuario_id = ?",
        (id, usuario_id),
    )
    conn.commit()
    conn.close()


def listar_agenda(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM agenda WHERE usuario_id = ? ORDER BY data ASC, horario ASC, id DESC",
        (usuario_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def criar_agenda(usuario_id, titulo, data, horario, categoria, status, descricao):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO agenda (usuario_id, titulo, data, horario, categoria, status, descricao) "
        "VALUES (?, ?, ?, ?, ?, ?, ?)",
        (usuario_id, titulo, data, horario, categoria, status, descricao),
    )
    conn.commit()
    conn.close()


def atualizar_agenda(usuario_id, agenda_id, titulo, data, horario, categoria, status, descricao):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE agenda SET titulo = ?, data = ?, horario = ?, categoria = ?, status = ?, descricao = ? "
        "WHERE id = ? AND usuario_id = ?",
        (titulo, data, horario, categoria, status, descricao, agenda_id, usuario_id),
    )
    alterada = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return alterada


def excluir_agenda(usuario_id, agenda_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM agenda WHERE id = ? AND usuario_id = ?", (agenda_id, usuario_id))
    excluida = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return excluida


def listar_metas(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT * FROM metas WHERE usuario_id = ? ORDER BY "
        "CASE status WHEN 'Ativa' THEN 0 WHEN 'Pausada' THEN 1 ELSE 2 END, "
        "CASE prioridade WHEN 'Alta' THEN 0 WHEN 'Média' THEN 1 ELSE 2 END, "
        "CASE WHEN data_limite IS NULL THEN 1 ELSE 0 END, data_limite, id DESC",
        (usuario_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def criar_meta(
    usuario_id, titulo, categoria, valor_alvo, valor_atual,
    data_limite, prioridade, status, descricao
):
    valor_alvo = Decimal(str(valor_alvo))
    valor_atual = Decimal(str(valor_atual))
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "INSERT INTO metas (usuario_id, titulo, categoria, valor_alvo, "
            "valor_atual, data_limite, prioridade, status, descricao) "
            "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id",
            (
                usuario_id, titulo, categoria, valor_alvo, valor_atual,
                data_limite, prioridade, status, descricao,
            ),
        )
        meta_id = cursor.fetchone()["id"]
        if valor_atual > 0:
            cursor.execute(
                "INSERT INTO meta_movimentacoes "
                "(meta_id, usuario_id, tipo, valor, descricao) "
                "VALUES (?, ?, 'Aporte', ?, 'Valor inicial')",
                (meta_id, usuario_id, valor_atual),
            )
        conn.commit()
        return meta_id
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def atualizar_meta(
    usuario_id, meta_id, titulo, categoria, valor_alvo,
    data_limite, prioridade, status, descricao
):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE metas SET titulo = ?, categoria = ?, valor_alvo = ?, "
        "data_limite = ?, prioridade = ?, "
        "status = CASE WHEN valor_atual >= ? THEN 'Concluída' "
        "WHEN ? = 'Concluída' THEN 'Ativa' ELSE ? END, descricao = ?, "
        "atualizado_em = CURRENT_TIMESTAMP WHERE id = ? AND usuario_id = ?",
        (
            titulo, categoria, Decimal(str(valor_alvo)), data_limite, prioridade,
            Decimal(str(valor_alvo)), status, status, descricao, meta_id, usuario_id,
        ),
    )
    alterada = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return alterada


def registrar_movimentacao_meta(usuario_id, meta_id, tipo, valor, descricao):
    valor = Decimal(str(valor))
    conn = conectar()
    cursor = conn.cursor()
    try:
        lock = " FOR UPDATE" if conn.postgres else ""
        cursor.execute(
            "SELECT valor_atual, valor_alvo, status FROM metas "
            "WHERE id = ? AND usuario_id = ?" + lock,
            (meta_id, usuario_id),
        )
        meta = cursor.fetchone()
        if not meta:
            conn.rollback()
            return None
        atual = Decimal(str(meta["valor_atual"]))
        alvo = Decimal(str(meta["valor_alvo"]))
        novo_valor = atual + valor if tipo == "Aporte" else atual - valor
        if novo_valor < 0:
            conn.rollback()
            raise ValueError("A retirada não pode ser maior que o valor acumulado.")
        status = meta["status"]
        if novo_valor >= alvo:
            status = "Concluída"
        elif status == "Concluída":
            status = "Ativa"
        cursor.execute(
            "UPDATE metas SET valor_atual = ?, status = ?, "
            "atualizado_em = CURRENT_TIMESTAMP WHERE id = ? AND usuario_id = ?",
            (novo_valor, status, meta_id, usuario_id),
        )
        cursor.execute(
            "INSERT INTO meta_movimentacoes "
            "(meta_id, usuario_id, tipo, valor, descricao) VALUES (?, ?, ?, ?, ?)",
            (meta_id, usuario_id, tipo, valor, descricao),
        )
        conn.commit()
        return novo_valor
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def listar_movimentacoes_meta(usuario_id, meta_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT mm.id, mm.tipo, mm.valor, mm.descricao, mm.criado_em "
        "FROM meta_movimentacoes mm JOIN metas m ON m.id = mm.meta_id "
        "WHERE mm.meta_id = ? AND mm.usuario_id = ? AND m.usuario_id = ? "
        "ORDER BY mm.id DESC LIMIT 100",
        (meta_id, usuario_id, usuario_id),
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def atualizar_status_meta(usuario_id, meta_id, status):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE metas SET status = CASE WHEN valor_atual >= valor_alvo "
        "THEN 'Concluída' ELSE ? END, atualizado_em = CURRENT_TIMESTAMP "
        "WHERE id = ? AND usuario_id = ?",
        (status, meta_id, usuario_id),
    )
    alterada = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return alterada


def excluir_meta(usuario_id, meta_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM metas WHERE id = ? AND usuario_id = ?",
        (meta_id, usuario_id),
    )
    excluida = cursor.rowcount > 0
    conn.commit()
    conn.close()
    return excluida


def healthcheck():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS ok")
    result = cursor.fetchone()
    conn.close()
    return result["ok"] == 1
