import os
import sqlite3

DB_NAME = "financeiro.db"
DATABASE_URL = os.getenv("DATABASE_URL")


class CursorAdapter:
    """Keep the existing SQLite-style queries portable to PostgreSQL."""

    def __init__(self, cursor, postgres=False):
        self._cursor = cursor
        self._postgres = postgres

    def execute(self, query, params=()):
        if self._postgres:
            query = query.replace("?", "%s")
        self._cursor.execute(query, params)
        return self

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    @property
    def lastrowid(self):
        return getattr(self._cursor, "lastrowid", None)


class ConnectionAdapter:
    def __init__(self, connection, postgres=False):
        self._connection = connection
        self._postgres = postgres

    def cursor(self):
        return CursorAdapter(self._connection.cursor(), self._postgres)

    def commit(self):
        self._connection.commit()

    def close(self):
        self._connection.close()

from werkzeug.security import (
    generate_password_hash,
    check_password_hash
)


# =========================
# CONEXÃO
# =========================

def conectar():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        conn = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            connect_timeout=10,
        )
        return ConnectionAdapter(conn, postgres=True)

    conn = sqlite3.connect(DB_NAME)
    conn.row_factory = sqlite3.Row
    return ConnectionAdapter(conn)


# =========================
# CRIAR TABELAS
# =========================

def criar_tabelas():

    conn = conectar()
    cursor = conn.cursor()

    id_column = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if DATABASE_URL
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS usuarios (
            id {id_column},
            nome TEXT NOT NULL,
            cpf TEXT UNIQUE,
            email TEXT NOT NULL UNIQUE,
            senha TEXT NOT NULL,
            perfil TEXT NOT NULL DEFAULT 'Padrão',
            ativo INTEGER NOT NULL DEFAULT 1
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS lancamentos (
            id {id_column},
            usuario_id INTEGER NOT NULL,
            data TEXT NOT NULL,
            tipo TEXT NOT NULL,
            descricao TEXT NOT NULL,
            valor REAL NOT NULL,
            obs TEXT,
            FOREIGN KEY(usuario_id)
            REFERENCES usuarios(id)
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS compras (
            id {id_column},
            usuario_id INTEGER NOT NULL,
            data TEXT NOT NULL,
            categoria TEXT NOT NULL,
            item TEXT NOT NULL,
            quantidade REAL NOT NULL,
            valor_unitario REAL NOT NULL,
            valor_total REAL NOT NULL,
            comprado INTEGER NOT NULL DEFAULT 0,
            obs TEXT,
            FOREIGN KEY(usuario_id)
            REFERENCES usuarios(id)
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS configuracoes (
            id {id_column},
            tipo_pix TEXT NOT NULL,
            chave_pix TEXT NOT NULL,
            nome_recebedor TEXT NOT NULL,
            banco TEXT NOT NULL,
            criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    cursor.execute(f"""
        CREATE TABLE IF NOT EXISTS solicitacoes_cadastro (
            id {id_column},
            cpf TEXT NOT NULL,
            email TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pendente',
            usuario_criado INTEGER NOT NULL DEFAULT 0,
            criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            pago_em TIMESTAMP
        )
    """)

    conn.commit()
    conn.close()


def criar_admin_inicial():
    """Seed exactly one admin when production credentials are configured."""
    email = os.getenv("ADMIN_EMAIL", "").strip().lower()
    senha = os.getenv("ADMIN_PASSWORD", "")
    nome = os.getenv("ADMIN_NAME", "Administrador").strip()

    if not email or not senha:
        return

    senha_hash = generate_password_hash(senha)
    conn = conectar()
    cursor = conn.cursor()

    if DATABASE_URL:
        cursor.execute("""
            INSERT INTO usuarios (nome, cpf, email, senha, perfil)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT (email) DO NOTHING
        """, (nome, None, email, senha_hash, "Administrativo"))
    else:
        cursor.execute("""
            INSERT OR IGNORE INTO usuarios (nome, cpf, email, senha, perfil)
            VALUES (?, ?, ?, ?, ?)
        """, (nome, None, email, senha_hash, "Administrativo"))

    conn.commit()
    conn.close()


# =========================
# USUÁRIOS
# =========================
def email_usuario_existe(email):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT COUNT(*) AS total
        FROM usuarios
        WHERE email = ?
    """, (email,))

    row = cursor.fetchone()
    existe = row["total"] > 0

    conn.close()

    return existe


def cpf_usuario_existe(cpf):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT COUNT(*) AS total
        FROM usuarios
        WHERE cpf = ?
    """, (cpf,))

    row = cursor.fetchone()
    existe = row["total"] > 0

    conn.close()

    return existe


def buscar_solicitacao_por_cpf(cpf):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM solicitacoes_cadastro
        WHERE cpf = ?
        ORDER BY id DESC
        LIMIT 1
    """, (cpf,))

    solicitacao = cursor.fetchone()

    conn.close()

    return dict(solicitacao) if solicitacao else None


def buscar_solicitacao_por_email(email):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM solicitacoes_cadastro
        WHERE email = ?
        ORDER BY id DESC
        LIMIT 1
    """, (email,))

    solicitacao = cursor.fetchone()

    conn.close()

    return dict(solicitacao) if solicitacao else None

def criar_usuario(nome, cpf, email, senha, perfil):

    senha_hash = generate_password_hash(senha)

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO usuarios
        (nome, cpf, email, senha, perfil)
        VALUES (?, ?, ?, ?, ?)
    """, (
        nome,
        cpf,
        email,
        senha_hash,
        perfil
    ))

    conn.commit()
    conn.close()

def buscar_usuario(email, senha):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT id, nome, email, senha, perfil, ativo
        FROM usuarios
        WHERE email = ?
    """, (email,))

    usuario = cursor.fetchone()

    conn.close()

    if not usuario:
        return None

    if usuario["ativo"] != 1:
        return None

    if check_password_hash(usuario["senha"], senha):

        return {
            "id": usuario["id"],
            "nome": usuario["nome"],
            "email": usuario["email"],
            "perfil": usuario["perfil"],
            "ativo": usuario["ativo"]
        }

    return None


def listar_usuarios():

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT
            id,
            nome,
            email,
            perfil,
            ativo
        FROM usuarios
        ORDER BY nome ASC
    """)

    usuarios = [
        dict(row)
        for row in cursor.fetchall()
    ]

    conn.close()

    return usuarios


def atualizar_perfil_usuario(usuario_id, perfil):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE usuarios
        SET perfil = ?
        WHERE id = ?
    """, (
        perfil,
        usuario_id
    ))

    conn.commit()
    conn.close()


def atualizar_status_usuario(usuario_id, ativo):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE usuarios
        SET ativo = ?
        WHERE id = ?
    """, (
        ativo,
        usuario_id
    ))

    conn.commit()
    conn.close()


def alterar_senha_usuario(usuario_id, nova_senha):

    senha_hash = generate_password_hash(nova_senha)

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE usuarios
        SET senha = ?
        WHERE id = ?
    """, (
        senha_hash,
        usuario_id
    ))

    conn.commit()
    conn.close()


def atualizar_dados_usuario(usuario_id, nome, email, perfil):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE usuarios
        SET
            nome = ?,
            email = ?,
            perfil = ?
        WHERE id = ?
    """, (
        nome,
        email,
        perfil,
        usuario_id
    ))

    conn.commit()
    conn.close()


def excluir_usuario(usuario_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        DELETE FROM lancamentos
        WHERE usuario_id = ?
    """, (usuario_id,))

    cursor.execute("""
        DELETE FROM compras
        WHERE usuario_id = ?
    """, (usuario_id,))

    cursor.execute("""
        DELETE FROM usuarios
        WHERE id = ?
    """, (usuario_id,))

    conn.commit()
    conn.close()


# =========================
# CONFIGURAÇÕES
# =========================

def buscar_configuracoes():

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM configuracoes
        LIMIT 1
    """)

    configuracao = cursor.fetchone()

    conn.close()

    if configuracao:
        return dict(configuracao)

    return None


def salvar_configuracoes(
    tipo_pix,
    chave_pix,
    nome_recebedor,
    banco
):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO configuracoes
        (
            tipo_pix,
            chave_pix,
            nome_recebedor,
            banco
        )
        VALUES (?, ?, ?, ?)
    """, (
        tipo_pix,
        chave_pix,
        nome_recebedor,
        banco
    ))

    conn.commit()
    conn.close()


def atualizar_configuracoes(
    tipo_pix,
    chave_pix,
    nome_recebedor,
    banco
):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE configuracoes
        SET
            tipo_pix = ?,
            chave_pix = ?,
            nome_recebedor = ?,
            banco = ?,
            atualizado_em = CURRENT_TIMESTAMP
        WHERE id = (
            SELECT id
            FROM configuracoes
            LIMIT 1
        )
    """, (
        tipo_pix,
        chave_pix,
        nome_recebedor,
        banco
    ))

    conn.commit()
    conn.close()


def existe_configuracao():

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT COUNT(*) AS total
        FROM configuracoes
    """)

    row = cursor.fetchone()
    existe = row["total"] > 0

    conn.close()

    return existe


# =========================
# SOLICITAÇÕES DE CADASTRO
# =========================

def criar_solicitacao_cadastro(cpf, email):

    conn = conectar()
    cursor = conn.cursor()

    returning = " RETURNING id" if DATABASE_URL else ""

    cursor.execute("""
        INSERT INTO solicitacoes_cadastro
        (
            cpf,
            email,
            status
        )
        VALUES (?, ?, ?)
    """ + returning, (
        cpf,
        email,
        "pendente"
    ))

    solicitacao_id = (
        cursor.fetchone()["id"]
        if DATABASE_URL
        else cursor.lastrowid
    )

    conn.commit()
    conn.close()

    return solicitacao_id


def buscar_solicitacao_cadastro(solicitacao_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM solicitacoes_cadastro
        WHERE id = ?
    """, (solicitacao_id,))

    solicitacao = cursor.fetchone()

    conn.close()

    if solicitacao:
        return dict(solicitacao)

    return None


def buscar_solicitacao_por_email(email):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM solicitacoes_cadastro
        WHERE email = ?
        ORDER BY id DESC
        LIMIT 1
    """, (email,))

    solicitacao = cursor.fetchone()

    conn.close()

    if solicitacao:
        return dict(solicitacao)

    return None


def marcar_solicitacao_como_paga(solicitacao_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE solicitacoes_cadastro
        SET
            status = 'pago',
            pago_em = CURRENT_TIMESTAMP
        WHERE id = ?
    """, (solicitacao_id,))

    conn.commit()
    conn.close()


def marcar_usuario_criado_solicitacao(solicitacao_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE solicitacoes_cadastro
        SET usuario_criado = 1
        WHERE id = ?
    """, (solicitacao_id,))

    conn.commit()
    conn.close()


def listar_solicitacoes_cadastro():

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM solicitacoes_cadastro
        ORDER BY id DESC
    """)

    solicitacoes = [
        dict(row)
        for row in cursor.fetchall()
    ]

    conn.close()

    return solicitacoes


# =========================
# LANÇAMENTOS
# =========================

def listar_lancamentos(usuario_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM lancamentos
        WHERE usuario_id = ?
        ORDER BY id DESC
    """, (usuario_id,))

    registros = [
        dict(row)
        for row in cursor.fetchall()
    ]

    conn.close()

    return registros


def listar_lancamentos_usuario(usuario_id):

    return listar_lancamentos(usuario_id)


def criar_lancamento(
    usuario_id,
    data,
    tipo,
    descricao,
    valor,
    obs
):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO lancamentos
        (
            usuario_id,
            data,
            tipo,
            descricao,
            valor,
            obs
        )
        VALUES (?, ?, ?, ?, ?, ?)
    """, (
        usuario_id,
        data,
        tipo,
        descricao,
        valor,
        obs
    ))

    conn.commit()
    conn.close()


def atualizar_lancamento(
    usuario_id,
    id,
    data,
    tipo,
    descricao,
    valor,
    obs
):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE lancamentos
        SET
            data = ?,
            tipo = ?,
            descricao = ?,
            valor = ?,
            obs = ?
        WHERE id = ?
        AND usuario_id = ?
    """, (
        data,
        tipo,
        descricao,
        valor,
        obs,
        id,
        usuario_id
    ))

    conn.commit()
    conn.close()


def excluir_lancamento(usuario_id, id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        DELETE FROM lancamentos
        WHERE id = ?
        AND usuario_id = ?
    """, (
        id,
        usuario_id
    ))

    conn.commit()
    conn.close()


# =========================
# COMPRAS
# =========================

def listar_compras(usuario_id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        SELECT *
        FROM compras
        WHERE usuario_id = ?
        ORDER BY id DESC
    """, (usuario_id,))

    registros = [
        dict(row)
        for row in cursor.fetchall()
    ]

    conn.close()

    return registros


def criar_compra(
    usuario_id,
    data,
    categoria,
    item,
    quantidade,
    valor_unitario,
    obs
):

    quantidade = float(quantidade)
    valor_unitario = float(valor_unitario)
    valor_total = quantidade * valor_unitario

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        INSERT INTO compras
        (
            usuario_id,
            data,
            categoria,
            item,
            quantidade,
            valor_unitario,
            valor_total,
            comprado,
            obs
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        usuario_id,
        data,
        categoria,
        item,
        quantidade,
        valor_unitario,
        valor_total,
        0,
        obs
    ))

    conn.commit()
    conn.close()


def atualizar_compra(
    usuario_id,
    id,
    data,
    categoria,
    item,
    quantidade,
    valor_unitario,
    obs
):

    quantidade = float(quantidade)
    valor_unitario = float(valor_unitario)
    valor_total = quantidade * valor_unitario

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE compras
        SET
            data = ?,
            categoria = ?,
            item = ?,
            quantidade = ?,
            valor_unitario = ?,
            valor_total = ?,
            obs = ?
        WHERE id = ?
        AND usuario_id = ?
    """, (
        data,
        categoria,
        item,
        quantidade,
        valor_unitario,
        valor_total,
        obs,
        id,
        usuario_id
    ))

    conn.commit()
    conn.close()


def atualizar_status_compra(usuario_id, id, comprado):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        UPDATE compras
        SET comprado = ?
        WHERE id = ?
        AND usuario_id = ?
    """, (
        comprado,
        id,
        usuario_id
    ))

    conn.commit()
    conn.close()


def excluir_compra(usuario_id, id):

    conn = conectar()
    cursor = conn.cursor()

    cursor.execute("""
        DELETE FROM compras
        WHERE id = ?
        AND usuario_id = ?
    """, (
        id,
        usuario_id
    ))

    conn.commit()
    conn.close()
