import os
import secrets
import sqlite3
import time
from datetime import date, datetime
from decimal import Decimal

from werkzeug.security import check_password_hash, generate_password_hash


DB_NAME = os.getenv("SQLITE_PATH", "financeiro.db")
DATABASE_URL = os.getenv("DATABASE_URL")


def _normalizar_valor(valor):
    if isinstance(valor, Decimal):
        return str(valor)
    if isinstance(valor, (date, datetime)):
        return valor.isoformat()
    return valor


def _normalizar_linha(linha):
    if linha is None:
        return None
    dados = dict(linha)
    return {chave: _normalizar_valor(valor) for chave, valor in dados.items()}


class CursorAdapter:
    def __init__(self, cursor, postgres=False):
        self._cursor = cursor
        self._postgres = postgres

    def execute(self, query, params=()):
        if self._postgres:
            query = query.replace("?", "%s")
            parametros = params
        else:
            parametros = tuple(_normalizar_valor(valor) for valor in params)
        self._cursor.execute(query, parametros)
        return self

    def executemany(self, query, params):
        if self._postgres:
            query = query.replace("?", "%s")
            parametros = params
        else:
            parametros = [
                tuple(_normalizar_valor(valor) for valor in linha) for linha in params
            ]
        self._cursor.executemany(query, parametros)
        return self

    def fetchone(self):
        return _normalizar_linha(self._cursor.fetchone())

    def fetchall(self):
        return [_normalizar_linha(row) for row in self._cursor.fetchall()]

    @property
    def rowcount(self):
        return self._cursor.rowcount

    @property
    def lastrowid(self):
        return getattr(self._cursor, "lastrowid", None)


class ConnectionAdapter:
    def __init__(self, connection, postgres=False):
        self._connection = connection
        self.postgres = postgres

    def cursor(self):
        return CursorAdapter(self._connection.cursor(), self.postgres)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def conectar():
    if DATABASE_URL:
        import psycopg
        from psycopg.rows import dict_row

        connection = psycopg.connect(
            DATABASE_URL,
            row_factory=dict_row,
            connect_timeout=10,
        )
        return ConnectionAdapter(connection, postgres=True)

    connection = sqlite3.connect(DB_NAME, timeout=10)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return ConnectionAdapter(connection)


def _colunas(cursor, tabela, postgres):
    if postgres:
        cursor.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ?",
            (tabela,),
        )
        return {row["column_name"] for row in cursor.fetchall()}
    cursor.execute(f"PRAGMA table_info({tabela})")
    return {row["name"] for row in cursor.fetchall()}


def executar_migracoes():
    """Apply versioned, idempotent schema migrations on startup."""
    conn = conectar()
    cursor = conn.cursor()
    postgres = conn.postgres
    identity = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if postgres
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    money = "NUMERIC(14,2)" if postgres else "NUMERIC"
    date_type = "DATE" if postgres else "TEXT"

    try:
        if postgres:
            cursor.execute("SELECT pg_advisory_xact_lock(184726391)")

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS schema_migrations (
                version INTEGER PRIMARY KEY,
                applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)

        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS usuarios (
                id {identity},
                nome TEXT NOT NULL,
                cpf TEXT UNIQUE,
                email TEXT NOT NULL UNIQUE,
                senha TEXT NOT NULL,
                perfil TEXT NOT NULL DEFAULT 'Padrão',
                ativo INTEGER NOT NULL DEFAULT 1,
                session_version INTEGER NOT NULL DEFAULT 1,
                must_change_password INTEGER NOT NULL DEFAULT 0,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS lancamentos (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                data {date_type} NOT NULL,
                tipo TEXT NOT NULL,
                descricao TEXT NOT NULL,
                valor {money} NOT NULL,
                obs TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS compras (
                id {identity},
                usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
                data {date_type} NOT NULL,
                categoria TEXT NOT NULL,
                item TEXT NOT NULL,
                quantidade {money} NOT NULL,
                valor_unitario {money} NOT NULL,
                valor_total {money} NOT NULL,
                comprado INTEGER NOT NULL DEFAULT 0,
                obs TEXT,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS configuracoes (
                id {identity},
                tipo_pix TEXT NOT NULL,
                chave_pix TEXT NOT NULL,
                nome_recebedor TEXT NOT NULL,
                banco TEXT NOT NULL,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
        """)
        cursor.execute(f"""
            CREATE TABLE IF NOT EXISTS solicitacoes_cadastro (
                id {identity},
                public_token TEXT UNIQUE,
                cpf TEXT NOT NULL,
                email TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'pendente',
                usuario_criado INTEGER NOT NULL DEFAULT 0,
                valor_centavos INTEGER NOT NULL DEFAULT 0,
                external_payment_id TEXT UNIQUE,
                criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                pago_em TIMESTAMP
            )
        """)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS rate_limits (
                chave TEXT PRIMARY KEY,
                tentativas INTEGER NOT NULL,
                janela_inicio INTEGER NOT NULL
            )
        """)

        timestamp_addition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP" if postgres else "TIMESTAMP"
        additions = {
            "usuarios": {
                "session_version": "INTEGER NOT NULL DEFAULT 1",
                "must_change_password": "INTEGER NOT NULL DEFAULT 0",
                "criado_em": timestamp_addition,
            },
            "lancamentos": {"criado_em": timestamp_addition},
            "compras": {"criado_em": timestamp_addition},
            "solicitacoes_cadastro": {
                "public_token": "TEXT",
                "valor_centavos": "INTEGER NOT NULL DEFAULT 0",
                "external_payment_id": "TEXT",
                "atualizado_em": timestamp_addition,
            },
        }
        for tabela, colunas in additions.items():
            existentes = _colunas(cursor, tabela, postgres)
            for coluna, definicao in colunas.items():
                if coluna not in existentes:
                    cursor.execute(
                        f"ALTER TABLE {tabela} ADD COLUMN {coluna} {definicao}"
                    )

        cursor.execute(
            "SELECT id FROM solicitacoes_cadastro "
            "WHERE public_token IS NULL OR public_token = ''"
        )
        for row in cursor.fetchall():
            cursor.execute(
                "UPDATE solicitacoes_cadastro SET public_token = ? WHERE id = ?",
                (secrets.token_urlsafe(32), row["id"]),
            )

        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (2,))
        migration_2_aplicada = cursor.fetchone() is not None
        if postgres and not migration_2_aplicada:
            cursor.execute(
                "ALTER TABLE lancamentos ALTER COLUMN valor TYPE NUMERIC(14,2) "
                "USING valor::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN quantidade TYPE NUMERIC(14,2) "
                "USING quantidade::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN valor_unitario TYPE NUMERIC(14,2) "
                "USING valor_unitario::numeric"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN valor_total TYPE NUMERIC(14,2) "
                "USING valor_total::numeric"
            )
        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (3,))
        migration_3_aplicada = cursor.fetchone() is not None
        if postgres and not migration_3_aplicada:
            cursor.execute(
                "ALTER TABLE lancamentos ALTER COLUMN data TYPE DATE USING data::date"
            )
            cursor.execute(
                "ALTER TABLE compras ALTER COLUMN data TYPE DATE USING data::date"
            )

        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitacoes_public_token "
            "ON solicitacoes_cadastro(public_token)"
        )
        cursor.execute(
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_solicitacoes_payment_id "
            "ON solicitacoes_cadastro(external_payment_id) "
            "WHERE external_payment_id IS NOT NULL"
        )

        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_lancamentos_usuario_data "
            "ON lancamentos(usuario_id, data)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_compras_usuario_data "
            "ON compras(usuario_id, data)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_solicitacoes_status "
            "ON solicitacoes_cadastro(status)"
        )

        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (4,))
        migration_4_aplicada = cursor.fetchone() is not None
        admin_email = os.getenv("ADMIN_EMAIL", "").strip().lower()
        admin_password = os.getenv("ADMIN_PASSWORD", "")
        if not migration_4_aplicada and admin_email and admin_password:
            cursor.execute(
                "UPDATE usuarios SET senha = ?, perfil = 'Administrativo', ativo = 1, "
                "must_change_password = 1, session_version = session_version + 1 "
                "WHERE email = ?",
                (generate_password_hash(admin_password), admin_email),
            )

        # Version 5 reapplies the one-time reset after correcting the production
        # secret. It remains idempotent and never runs again after being recorded.
        cursor.execute("SELECT version FROM schema_migrations WHERE version = ?", (5,))
        migration_5_aplicada = cursor.fetchone() is not None
        if not migration_5_aplicada and admin_email and admin_password:
            cursor.execute(
                "UPDATE usuarios SET senha = ?, perfil = 'Administrativo', ativo = 1, "
                "must_change_password = 1, session_version = session_version + 1 "
                "WHERE email = ?",
                (generate_password_hash(admin_password), admin_email),
            )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (1,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (2,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (3,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (4,),
        )
        cursor.execute(
            "INSERT INTO schema_migrations(version) VALUES (?) "
            "ON CONFLICT(version) DO NOTHING",
            (5,),
        )
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def criar_tabelas():
    executar_migracoes()


def criar_admin_inicial():
    email = os.getenv("ADMIN_EMAIL", "").strip().lower()
    senha = os.getenv("ADMIN_PASSWORD", "")
    nome = os.getenv("ADMIN_NAME", "Administrador").strip()
    if not email or not senha:
        return

    conn = conectar()
    cursor = conn.cursor()
    try:
        command = "INSERT INTO" if conn.postgres else "INSERT OR IGNORE INTO"
        suffix = " ON CONFLICT (email) DO NOTHING" if conn.postgres else ""
        cursor.execute(
            f"{command} usuarios "
            "(nome, cpf, email, senha, perfil, must_change_password) "
            "VALUES (?, ?, ?, ?, ?, ?)" + suffix,
            (nome, None, email, generate_password_hash(senha), "Administrativo", 1),
        )
        cursor.execute("SELECT id, senha FROM usuarios WHERE email = ?", (email,))
        existente = cursor.fetchone()
        if existente and check_password_hash(existente["senha"], senha):
            cursor.execute(
                "UPDATE usuarios SET must_change_password = 1 WHERE id = ?",
                (existente["id"],),
            )
        conn.commit()
    finally:
        conn.close()


def buscar_usuario(email, senha):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, senha, perfil, ativo, session_version, "
        "must_change_password FROM usuarios WHERE email = ?",
        (email.strip().lower(),),
    )
    usuario = cursor.fetchone()
    conn.close()
    if not usuario or usuario["ativo"] != 1:
        return None
    if not check_password_hash(usuario["senha"], senha):
        return None
    usuario.pop("senha", None)
    return usuario


def buscar_usuario_por_id(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, perfil, ativo, session_version, "
        "must_change_password FROM usuarios WHERE id = ?",
        (usuario_id,),
    )
    usuario = cursor.fetchone()
    conn.close()
    return usuario


def listar_usuarios():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT id, nome, email, perfil, ativo, must_change_password "
        "FROM usuarios ORDER BY nome ASC"
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def criar_usuario(nome, cpf, email, senha, perfil, must_change_password=0):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO usuarios "
        "(nome, cpf, email, senha, perfil, must_change_password) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (
            nome,
            cpf,
            email.strip().lower(),
            generate_password_hash(senha),
            perfil,
            must_change_password,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_dados_usuario(usuario_id, nome, email, perfil):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET nome = ?, email = ?, perfil = ?, "
        "session_version = session_version + 1 WHERE id = ?",
        (nome, email.strip().lower(), perfil, usuario_id),
    )
    conn.commit()
    conn.close()


def atualizar_status_usuario(usuario_id, ativo):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET ativo = ?, session_version = session_version + 1 "
        "WHERE id = ?",
        (1 if ativo else 0, usuario_id),
    )
    conn.commit()
    conn.close()


def alterar_senha_usuario(usuario_id, nova_senha, force_change=1):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE usuarios SET senha = ?, must_change_password = ?, "
        "session_version = session_version + 1 WHERE id = ?",
        (generate_password_hash(nova_senha), force_change, usuario_id),
    )
    conn.commit()
    conn.close()


def alterar_senha_propria(usuario_id, senha_atual, nova_senha):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT senha, session_version FROM usuarios WHERE id = ? AND ativo = 1",
        (usuario_id,),
    )
    usuario = cursor.fetchone()
    if not usuario or not check_password_hash(usuario["senha"], senha_atual):
        conn.close()
        return None
    nova_versao = int(usuario["session_version"]) + 1
    cursor.execute(
        "UPDATE usuarios SET senha = ?, must_change_password = 0, "
        "session_version = ? WHERE id = ?",
        (generate_password_hash(nova_senha), nova_versao, usuario_id),
    )
    conn.commit()
    conn.close()
    return nova_versao


def excluir_usuario(usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute("DELETE FROM lancamentos WHERE usuario_id = ?", (usuario_id,))
        cursor.execute("DELETE FROM compras WHERE usuario_id = ?", (usuario_id,))
        cursor.execute("DELETE FROM usuarios WHERE id = ?", (usuario_id,))
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def buscar_configuracoes():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM configuracoes ORDER BY id LIMIT 1")
    row = cursor.fetchone()
    conn.close()
    return row


def salvar_ou_atualizar_configuracoes(tipo_pix, chave_pix, nome_recebedor, banco):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT id FROM configuracoes ORDER BY id LIMIT 1")
    existente = cursor.fetchone()
    if existente:
        cursor.execute(
            "UPDATE configuracoes SET tipo_pix = ?, chave_pix = ?, "
            "nome_recebedor = ?, banco = ?, atualizado_em = CURRENT_TIMESTAMP "
            "WHERE id = ?",
            (tipo_pix, chave_pix, nome_recebedor, banco, existente["id"]),
        )
    else:
        cursor.execute(
            "INSERT INTO configuracoes "
            "(tipo_pix, chave_pix, nome_recebedor, banco) VALUES (?, ?, ?, ?)",
            (tipo_pix, chave_pix, nome_recebedor, banco),
        )
    conn.commit()
    conn.close()


def email_usuario_existe(email):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS existe FROM usuarios WHERE email = ?", (email,))
    existe = cursor.fetchone() is not None
    conn.close()
    return existe


def cpf_usuario_existe(cpf):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS existe FROM usuarios WHERE cpf = ?", (cpf,))
    existe = cursor.fetchone() is not None
    conn.close()
    return existe


def criar_ou_buscar_solicitacao(cpf, email, valor_centavos):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT public_token, status FROM solicitacoes_cadastro "
        "WHERE cpf = ? AND email = ? ORDER BY id DESC LIMIT 1",
        (cpf, email),
    )
    existente = cursor.fetchone()
    if existente:
        conn.close()
        return existente

    token = secrets.token_urlsafe(32)
    returning = " RETURNING public_token, status" if conn.postgres else ""
    cursor.execute(
        "INSERT INTO solicitacoes_cadastro "
        "(public_token, cpf, email, valor_centavos) VALUES (?, ?, ?, ?)" + returning,
        (token, cpf, email, valor_centavos),
    )
    if conn.postgres:
        row = cursor.fetchone()
    else:
        row = {"public_token": token, "status": "pendente"}
    conn.commit()
    conn.close()
    return row


def buscar_status_solicitacao(token):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "SELECT public_token, status, usuario_criado FROM solicitacoes_cadastro "
        "WHERE public_token = ?",
        (token,),
    )
    row = cursor.fetchone()
    conn.close()
    return row


def confirmar_pagamento(token, external_payment_id, valor_centavos):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE solicitacoes_cadastro SET status = 'pago', pago_em = CURRENT_TIMESTAMP, "
        "atualizado_em = CURRENT_TIMESTAMP, external_payment_id = ? "
        "WHERE public_token = ? AND valor_centavos = ? AND status = 'pendente'",
        (external_payment_id, token, valor_centavos),
    )
    alteradas = cursor.rowcount
    conn.commit()
    conn.close()
    return alteradas == 1


def finalizar_cadastro(token, nome, email, senha):
    conn = conectar()
    cursor = conn.cursor()
    try:
        lock = " FOR UPDATE" if conn.postgres else ""
        cursor.execute(
            "SELECT cpf, email, status, usuario_criado FROM solicitacoes_cadastro "
            "WHERE public_token = ?" + lock,
            (token,),
        )
        solicitacao = cursor.fetchone()
        if not solicitacao:
            return "nao_encontrada"
        if solicitacao["status"] != "pago":
            return "nao_pago"
        if solicitacao["usuario_criado"] == 1:
            return "ja_criado"
        if solicitacao["email"].lower() != email.lower():
            return "email_invalido"

        cursor.execute(
            "INSERT INTO usuarios (nome, cpf, email, senha, perfil) "
            "VALUES (?, ?, ?, ?, ?)",
            (
                nome,
                solicitacao["cpf"],
                email.lower(),
                generate_password_hash(senha),
                "Padrão",
            ),
        )
        cursor.execute(
            "UPDATE solicitacoes_cadastro SET usuario_criado = 1, "
            "atualizado_em = CURRENT_TIMESTAMP WHERE public_token = ?",
            (token,),
        )
        conn.commit()
        return "ok"
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def rate_limit_permitir(chave, limite, janela_segundos):
    agora = int(time.time())
    conn = conectar()
    cursor = conn.cursor()
    try:
        cursor.execute(
            "INSERT INTO rate_limits(chave, tentativas, janela_inicio) "
            "VALUES (?, 1, ?) ON CONFLICT(chave) DO UPDATE SET "
            "tentativas = CASE WHEN ? - rate_limits.janela_inicio >= ? "
            "THEN 1 ELSE rate_limits.tentativas + 1 END, "
            "janela_inicio = CASE WHEN ? - rate_limits.janela_inicio >= ? "
            "THEN ? ELSE rate_limits.janela_inicio END "
            "RETURNING tentativas",
            (chave, agora, agora, janela_segundos, agora, janela_segundos, agora),
        )
        row = cursor.fetchone()
        cursor.execute(
            "DELETE FROM rate_limits WHERE janela_inicio < ?",
            (agora - 7 * 24 * 60 * 60,),
        )
        conn.commit()
        return int(row["tentativas"]) <= limite
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def rate_limit_limpar(chave):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("DELETE FROM rate_limits WHERE chave = ?", (chave,))
    conn.commit()
    conn.close()


def _listar_por_usuario(tabela, usuario_id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        f"SELECT * FROM {tabela} WHERE usuario_id = ? ORDER BY id DESC",
        (usuario_id,),
    )
    rows = cursor.fetchall()
    conn.close()
    return rows


def listar_lancamentos(usuario_id):
    return _listar_por_usuario("lancamentos", usuario_id)


def criar_lancamento(usuario_id, data, tipo, descricao, valor, obs):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO lancamentos "
        "(usuario_id, data, tipo, descricao, valor, obs) VALUES (?, ?, ?, ?, ?, ?)",
        (usuario_id, data, tipo, descricao, Decimal(str(valor)), obs),
    )
    conn.commit()
    conn.close()


def atualizar_lancamento(usuario_id, id, data, tipo, descricao, valor, obs):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE lancamentos SET data = ?, tipo = ?, descricao = ?, valor = ?, obs = ? "
        "WHERE id = ? AND usuario_id = ?",
        (data, tipo, descricao, Decimal(str(valor)), obs, id, usuario_id),
    )
    conn.commit()
    conn.close()


def excluir_lancamento(usuario_id, id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM lancamentos WHERE id = ? AND usuario_id = ?",
        (id, usuario_id),
    )
    conn.commit()
    conn.close()


def listar_compras(usuario_id):
    return _listar_por_usuario("compras", usuario_id)


def criar_compra(usuario_id, data, categoria, item, quantidade, valor_unitario, obs):
    quantidade = Decimal(str(quantidade))
    valor_unitario = Decimal(str(valor_unitario))
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "INSERT INTO compras (usuario_id, data, categoria, item, quantidade, "
        "valor_unitario, valor_total, comprado, obs) VALUES (?, ?, ?, ?, ?, ?, ?, 0, ?)",
        (
            usuario_id,
            data,
            categoria,
            item,
            quantidade,
            valor_unitario,
            quantidade * valor_unitario,
            obs,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_compra(usuario_id, id, data, categoria, item, quantidade, valor_unitario, obs):
    quantidade = Decimal(str(quantidade))
    valor_unitario = Decimal(str(valor_unitario))
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE compras SET data = ?, categoria = ?, item = ?, quantidade = ?, "
        "valor_unitario = ?, valor_total = ?, obs = ? WHERE id = ? AND usuario_id = ?",
        (
            data,
            categoria,
            item,
            quantidade,
            valor_unitario,
            quantidade * valor_unitario,
            obs,
            id,
            usuario_id,
        ),
    )
    conn.commit()
    conn.close()


def atualizar_status_compra(usuario_id, id, comprado):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "UPDATE compras SET comprado = ? WHERE id = ? AND usuario_id = ?",
        (1 if comprado else 0, id, usuario_id),
    )
    conn.commit()
    conn.close()


def excluir_compra(usuario_id, id):
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute(
        "DELETE FROM compras WHERE id = ? AND usuario_id = ?",
        (id, usuario_id),
    )
    conn.commit()
    conn.close()


def healthcheck():
    conn = conectar()
    cursor = conn.cursor()
    cursor.execute("SELECT 1 AS ok")
    result = cursor.fetchone()
    conn.close()
    return result["ok"] == 1
